[package]
name = "btl"
version.workspace = true
edition.workspace = true

[[bin]]
name = "btl"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full", "rt-multi-thread", "macros"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "uuid", "macros"] }
dotenvy = "0.15"
anyhow = "1"
uuid = { version = "1", features = ["v4"] }
thiserror = "2"